"use client";
import { useEffect, useRef, useState } from "react";
import { AlertTriangle, BookOpen, Check, CheckCircle2, ChevronRight, CircleUserRound, Copy, Download, FileCheck2, FileText, FolderOpen, Highlighter, LayoutDashboard, Pencil, Plane, Plus, Save, Scale, Search, ShieldCheck, Sparkles, Trash2, UploadCloud, UserCog, Users, X } from "lucide-react";

type Tab = "visao"|"partes"|"citacoes"|"teses"|"provas"|"riscos";
type View = "analises"|"documentos"|"biblioteca"|"citacoes-salvas"|"banco-teses";
type SavedCitation={id:string;title:string;text:string;source:string;notes:string};
type SavedThesis={id:string;title:string;summary:string;foundation:string};
type Profile={name:string;email:string;oab:string;office:string};
const tabs:[Tab,string,number?][]=[["visao","Visão geral"],["partes","Partes",2],["citacoes","Citações",4],["teses","Teses",3],["provas","Provas",5],["riscos","Riscos",2]];
const parties=[["Parte autora","PARTE AUTORA","Passageiro · engenheiro · qualificação na página 1","MA"],["Parte ré","COMPANHIA AÉREA RÉ","Transportadora aérea · qualificação na página 1","VB"]];
const citations=[
 ["1","Cancelamento do voo","Ocorre que o voo foi cancelado pela companhia aérea, sem que fosse oferecida solução adequada e tempestiva ao passageiro.","Comprovação do fato gerador narrado."],
 ["1","Atraso total","O transporte somente foi concluído em 19 de agosto de 2026, às 17h10, após reacomodação em voo diverso, ocasionando atraso de aproximadamente 24 horas e 30 minutos em relação ao itinerário originalmente contratado.","Delimitação temporal do atraso alegado."],
 ["1","Ausência de assistência","O Autor perdeu reunião profissional previamente agendada em Salvador, precisou pernoitar por conta própria em Campinas e não recebeu da Ré alimentação, hospedagem ou transporte adequados.","Individualização dos prejuízos narrados."],
 ["1","Danos materiais","Em razão direta do ocorrido, o Autor suportou despesas no valor de R$ 1.284,60.","Quantificação do ressarcimento pretendido."]
];
const theses=[
 ["Forte","Responsabilidade objetiva e falha do serviço","A petição sustenta cancelamento, reacomodação tardia e ausência de informação adequada.","Narrativa da página 1 · CDC, art. 14"],
 ["Forte","Danos materiais","A inicial pede ressarcimento de R$ 1.284,60 por hospedagem, alimentação, transporte e remarcação.","Fatos e pedido d da página 8"],
 ["Moderada","Dano moral individualizado","A tese se apoia em atraso de 24h30, pernoite involuntário e perda de reunião profissional.","Fatos da página 1 · fundamentação das páginas 6 e 7"]
];

export default function Home(){
 const input=useRef<HTMLInputElement>(null); const [file,setFile]=useState("49381320-f03c-4e5e-8c4c-09d3a3f727dd(1).pdf"); const [originalFile,setOriginalFile]=useState<File|null>(null); const [tab,setTab]=useState<Tab>("visao"); const [done,setDone]=useState(true); const [loading,setLoading]=useState(false); const [blocked,setBlocked]=useState(false); const [copied,setCopied]=useState("");
 const [view,setView]=useState<View>("analises");
 const [savedCitations,setSavedCitations]=useState<SavedCitation[]>([]);
 const [savedTheses,setSavedTheses]=useState<SavedThesis[]>([]);
 const [profile,setProfile]=useState<Profile>({name:"Usuário AeroLex",email:"usuario@exemplo.com",oab:"",office:""});
 const [profileOpen,setProfileOpen]=useState(false); const [toast,setToast]=useState("");
 useEffect(()=>{try{const c=localStorage.getItem("aerolex-citations"),t=localStorage.getItem("aerolex-theses"),p=localStorage.getItem("aerolex-profile");if(c)setSavedCitations(JSON.parse(c));if(t)setSavedTheses(JSON.parse(t));if(p)setProfile(JSON.parse(p))}catch{}},[]);
 const persistCitations=(items:SavedCitation[])=>{setSavedCitations(items);localStorage.setItem("aerolex-citations",JSON.stringify(items))};
 const persistTheses=(items:SavedThesis[])=>{setSavedTheses(items);localStorage.setItem("aerolex-theses",JSON.stringify(items))};
 const notify=(message:string)=>{setToast(message);setTimeout(()=>setToast(""),1800)};
 const saveCitation=(title:string,text:string,source="Documento analisado")=>{if(savedCitations.some(x=>x.text===text)){notify("Esta citação já está salva");return}persistCitations([...savedCitations,{id:crypto.randomUUID(),title,text,source,notes:""}]);notify("Citação salva")};
 const saveThesis=(title:string,summary:string,foundation:string)=>{if(savedTheses.some(x=>x.title===title)){notify("Esta tese já está no banco");return}persistTheses([...savedTheses,{id:crypto.randomUUID(),title,summary,foundation}]);notify("Tese adicionada ao banco")};
 const pick=(f?:File)=>{if(f){setFile(f.name);setOriginalFile(f);setDone(false);setBlocked(false);setTab("visao")}};
 const analyze=()=>{setLoading(true);setBlocked(false);setTimeout(()=>{setLoading(false);setDone(false);setBlocked(true)},1200)};
 const copy=(id:string,text:string)=>{navigator.clipboard?.writeText(text);setCopied(id);setTimeout(()=>setCopied(""),1200)};
 const downloadBlob=(blob:Blob,name:string)=>{const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download=name;a.target="_blank";a.rel="noopener";document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(u),30000)};
 const exportFile=()=>{const text=`AEROLEX — ANÁLISE JURÍDICA\r\nDocumento: ${file}\r\n\r\nPARTES\r\n${parties.map(p=>p[0]+": "+p[1]).join("\r\n")}\r\n\r\nCITAÇÕES\r\n${citations.map(c=>"Página "+c[0]+': “'+c[2]+'”').join("\r\n\r\n")}\r\n\r\nTESES\r\n${theses.map(t=>t[1]+": "+t[2]).join("\r\n\r\n")}\r\n\r\nRevisão humana obrigatória.`;downloadBlob(new Blob(["\\ufeff",text],{type:"text/plain;charset=utf-8"}),"analise-aerolex.txt")};
 const downloadOriginal=()=>{if(originalFile){downloadBlob(originalFile,originalFile.name);return}const a=document.createElement("a");a.href="/documento-original.pdf";a.download="peticao-inicial-original.pdf";document.body.appendChild(a);a.click();a.remove()};
 const downloadAnnotated=()=>{const a=document.createElement("a");a.href="/documento-analisado-marcado.pdf";a.download="peticao-inicial-analisada-aerolex.pdf";document.body.appendChild(a);a.click();a.remove()};
 return <main className="shell">
  <header><div className="brand"><b><Plane size={19}/></b><span><strong>AeroLex</strong><small>Inteligência jurídica</small></span></div><button className="search" onClick={()=>setView("documentos")}><Search size={15}/> Buscar documentos <kbd>⌘ K</kbd></button><button className="circle profile-button" onClick={()=>setProfileOpen(true)} title="Configurar perfil"><span>{initials(profile.name)}</span></button></header>
  <aside><button className="new" onClick={()=>{setView("analises");input.current?.click()}}><Plus size={16}/> Nova análise</button><nav><label>Espaço de trabalho</label><Nav active={view==="analises"} onClick={()=>setView("analises")} icon={<LayoutDashboard size={16}/>} label="Análises"/><Nav active={view==="documentos"} onClick={()=>setView("documentos")} icon={<FolderOpen size={16}/>} label="Documentos"/><Nav active={view==="biblioteca"} onClick={()=>setView("biblioteca")} icon={<BookOpen size={16}/>} label="Biblioteca jurídica"/><label>Ferramentas</label><Nav active={view==="citacoes-salvas"} onClick={()=>setView("citacoes-salvas")} icon={<Highlighter size={16}/>} label="Citações salvas" count={savedCitations.length}/><Nav active={view==="banco-teses"} onClick={()=>setView("banco-teses")} icon={<Scale size={16}/>} label="Banco de teses" count={savedTheses.length}/></nav><div className="privacy"><ShieldCheck size={18}/><span><strong>Ambiente confidencial</strong><small>Revise a análise antes do uso profissional.</small></span></div></aside>
  <input ref={input} type="file" accept=".pdf,.doc,.docx,.txt" hidden onChange={e=>pick(e.target.files?.[0])}/>
  {view==="analises"?<section className="workspace">
   <div className="title"><div><p>Análises <ChevronRight size={12}/> Documento aéreo</p><h1>Leitura jurídica do documento</h1><span>Extração estruturada com rastreabilidade até o trecho original.</span></div><button onClick={exportFile} disabled={!done||!!originalFile}><Download size={15}/> Exportar análise</button></div>
   <div className="file"><i><FileText size={23}/></i><span><strong>{file}</strong><small>{originalFile?"Arquivo enviado · ainda não analisado":"8 páginas · análise extraída e revisada"}</small></span><em className={done&&!originalFile?"ok":""}>{done&&!originalFile?<CheckCircle2 size={14}/>:<UploadCloud size={14}/>} {done&&!originalFile?"Análise validada":"Aguardando análise pelo chat"}</em><button onClick={()=>input.current?.click()}>Substituir</button>{originalFile&&!blocked&&<button className="primary" onClick={analyze}><Sparkles size={15}/> Analisar</button>}</div>
   {loading?<Loading/>:blocked?<Blocked pick={()=>input.current?.click()}/>:done&&!originalFile?<><div className="tabs">{tabs.map(t=><button className={tab===t[0]?"on":""} onClick={()=>setTab(t[0])} key={t[0]}>{t[1]} {t[2]&&<b>{t[2]}</b>}</button>)}</div><div className="grid"><article className="panel">{tab==="visao"&&<Overview setTab={setTab}/>} {tab==="partes"&&<Parties/>} {tab==="citacoes"&&<Citations copy={copy} copied={copied} save={saveCitation}/>} {tab==="teses"&&<Theses save={saveThesis}/>} {tab==="provas"&&<Evidence/>} {tab==="riscos"&&<Risks/>}</article><Source/></div></>:<Empty analyze={analyze} pick={()=>input.current?.click()}/>} 
  </section>:<SectionView view={view} file={file} setView={setView} savedCitations={savedCitations} persistCitations={persistCitations} savedTheses={savedTheses} persistTheses={persistTheses} saveCitation={saveCitation} input={input}/>} 
  {profileOpen&&<ProfileModal profile={profile} close={()=>setProfileOpen(false)} save={p=>{setProfile(p);localStorage.setItem("aerolex-profile",JSON.stringify(p));setProfileOpen(false);notify("Perfil atualizado")}}/>}
  {toast&&<div className="toast"><CheckCircle2/> {toast}</div>}
 </main>
}

function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"U"}
function Nav({active,onClick,icon,label,count}:{active:boolean;onClick:()=>void;icon:React.ReactNode;label:string;count?:number}){return <button className={active?"nav-item on":"nav-item"} onClick={onClick}>{icon}<span>{label}</span>{count!==undefined&&count>0?<b>{count}</b>:null}</button>}

function Head({over,title}:{over:string,title:string}){return <div className="head"><small>{over}</small><h2>{title}</h2></div>}
function Overview({setTab}:{setTab:(t:Tab)=>void}){return <><Head over="Síntese da análise" title="Cancelamento de voo e atraso de 24 horas e 30 minutos"/><p className="lead">PARTE AUTORA ajuíza ação indenizatória contra COMPANHIA AÉREA RÉ A petição relata cancelamento do trecho Campinas–Salvador, reacomodação no dia seguinte, ausência de assistência material, perda de reunião profissional e despesas de R$ 1.284,60.</p><div className="metrics"><button onClick={()=>setTab("partes")}><Users/> <span><b>2</b> partes identificadas</span></button><button onClick={()=>setTab("citacoes")}><Highlighter/> <span><b>4</b> trechos citáveis</span></button><button onClick={()=>setTab("teses")}><Scale/> <span><b>3</b> teses principais</span></button></div><hr/><Head over="Cronologia extraída" title="Sequência dos fatos"/><div className="timeline"><p><small>18 AGO 2026 · 14h20</small><b>Embarque originalmente previsto</b><span>Trecho Campinas/SP–Salvador/BA, chegada prevista às 16h40.</span></p><p><small>18 AGO 2026</small><b>Cancelamento e espera</b><span>A inicial afirma ausência de solução tempestiva e assistência adequada.</span></p><p><small>19 AGO 2026 · 17h10</small><b>Transporte concluído</b><span>Chegada após reacomodação, com atraso aproximado de 24h30.</span></p></div><div className="warning"><AlertTriangle/><span><b>Ponto que exige confirmação</b><small>O PDF menciona comprovantes anexos, mas contém apenas a petição. Os anexos não foram apresentados para conferência.</small></span></div></>}
function Parties(){return <><Head over="Sujeitos da relação" title="Partes identificadas"/><div className="cards parties">{parties.map((p,i)=><section key={p[1]}><i className={i?"dark":""}>{p[3]}</i><span><small>{p[0]}</small><b>{p[1]}</b><em>{p[2]}</em></span><label><CheckCircle2/> Alta confiança</label></section>)}</div><div className="notice"><FileCheck2/><span><b>Critério de identificação</b><small>Nomes e papéis processuais localizados no preâmbulo e conferidos com o bilhete.</small></span></div></>}
function Citations({copy,copied,save}:{copy:(a:string,b:string)=>void;copied:string;save:(a:string,b:string,c?:string)=>void}){return <><Head over="Trechos rastreáveis" title="Citações relevantes"/><p className="intro">Copie um trecho ou salve-o na sua coleção para reutilizar em outras peças.</p><div className="cards citations">{citations.map(c=><section key={c[1]}><div><small>Página {c[0]}</small><span className="card-actions"><button onClick={()=>save(c[1],c[2],`Petição inicial · página ${c[0]}`)}><Save/> Salvar</button><button onClick={()=>copy(c[1],c[2])}>{copied===c[1]?<Check/>:<Copy/>} {copied===c[1]?"Copiado":"Copiar"}</button></span></div><b>{c[1]}</b><blockquote>“{c[2]}”</blockquote><p><strong>Utilidade:</strong> {c[3]}</p></section>)}</div></>}
function Theses({save}:{save:(a:string,b:string,c:string)=>void}){return <><Head over="Construção argumentativa" title="Principais teses identificadas"/><p className="intro">Revise a hipótese e salve-a no banco para reaproveitar sua estrutura.</p><div className="cards theses">{theses.map((t,i)=><section key={t[1]}><i>0{i+1}</i><span><div><b>{t[1]}</b><span className="thesis-tools"><label className={t[0]==="Forte"?"green":""}>{t[0]}</label><button onClick={()=>save(t[1],t[2],t[3])}><Save/> Salvar</button></span></div><p>{t[2]}</p><small><FileCheck2/> Base documental: {t[3]}</small></span></section>)}</div></>}
function Evidence(){const e=[["Bilhete eletrônico","Mencionado como comprovante do itinerário","Mencionado"],["Comprovante de reacomodação","Necessário para confirmar a chegada","Mencionado"],["Protocolo PROTOCOLO-SUPRIMIDO","Reclamação administrativa indicada na inicial","Mencionado"],["Recibos de R$ 1.284,60","Alegados para quantificar os danos materiais","Mencionado"],["Anexos comprobatórios","Não integram o PDF recebido","Ausente"]];return <><Head over="Matriz documental" title="Provas mencionadas e ausentes"/><div className="evidence">{e.map(x=><p key={x[0]}><FileText/><span><b>{x[0]}</b><small>{x[1]}</small></span><em className={x[2]==="Ausente"?"miss":""}>{x[2]}</em></p>)}</div></>}
function Risks(){return <><Head over="Revisão crítica" title="Riscos e lacunas da narrativa"/><div className="cards risks"><section><AlertTriangle/><span><small>Risco probatório</small><b>Motivo do cancelamento não documentado</b><p>Sem a comunicação formal, não é possível avaliar eventual excludente alegada pela companhia.</p></span></section><section><AlertTriangle/><span><small>Documentação ausente</small><b>Comprovantes mencionados não foram enviados</b><p>O PDF contém apenas a petição. Bilhete, recibos, protocolo e prova da reunião precisam ser conferidos separadamente.</p></span></section></div></>}
function Source(){return <aside className="source"><div className="source-head"><span><b>Documento analisado</b><small>Miniatura da página 1 do PDF</small></span></div><div className="pdf-preview"><img src="/documento-miniatura.png" alt="Página 1 do documento jurídico analisado"/></div><div className="mark-legend"><span><i className="mark thesis"/> Teses</span><span><i className="mark evidence-mark"/> Provas</span><span><i className="mark quote-mark"/> Citações</span></div><div className="download-stack"><a href="/documento-original.pdf" download="peticao-inicial-original.pdf"><FileText/> <span>Baixar documento original</span> <Download/></a><a className="marked-download" href="/documento-analisado-marcado.pdf" download="peticao-inicial-analisada-aerolex.pdf"><Highlighter/> <span>Baixar documento analisado</span> <Download/></a></div><small><ShieldCheck/> O PDF analisado contém 10 marcações rastreáveis nas 8 páginas.</small></aside>}

function SectionView({view,file,setView,savedCitations,persistCitations,savedTheses,persistTheses,saveCitation,input}:{view:View;file:string;setView:(v:View)=>void;savedCitations:SavedCitation[];persistCitations:(x:SavedCitation[])=>void;savedTheses:SavedThesis[];persistTheses:(x:SavedThesis[])=>void;saveCitation:(a:string,b:string,c?:string)=>void;input:React.RefObject<HTMLInputElement|null>}){
 const [query,setQuery]=useState("");
 const titles:Record<Exclude<View,"analises">,[string,string]>={documentos:["Documentos","Arquivos enviados e vinculados às suas análises."],biblioteca:["Biblioteca jurídica","Referências essenciais para pesquisa em Direito Aéreo."],"citacoes-salvas":["Citações salvas","Trechos de jurisprudência e documentos para reutilização."],"banco-teses":["Banco de teses","Argumentos jurídicos organizados para suas próximas peças."]};
 const [title,subtitle]=titles[view as Exclude<View,"analises">];
 return <section className="workspace section-page"><div className="section-title"><div><small>Espaço de trabalho</small><h1>{title}</h1><p>{subtitle}</p></div>{view==="documentos"&&<button className="primary action-button" onClick={()=>input.current?.click()}><Plus/> Adicionar documento</button>}</div>
  <div className="section-toolbar"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Buscar em ${title.toLowerCase()}`}/></div>
  {view==="documentos"&&<div className="document-table"><div className="table-head"><span>Documento</span><span>Status</span><span>Tipo</span><span></span></div><div className="table-row"><i><FileText/></i><span><b>{file}</b><small>Adicionado hoje · 8 páginas</small></span><em>Análise validada</em><small>Petição inicial</small><button onClick={()=>setView("analises")}>Abrir <ChevronRight/></button></div></div>}
  {view==="biblioteca"&&<Library query={query} saveCitation={saveCitation}/>} 
  {view==="citacoes-salvas"&&<SavedCitations items={savedCitations.filter(x=>(x.title+x.text+x.source).toLowerCase().includes(query.toLowerCase()))} update={persistCitations}/>} 
  {view==="banco-teses"&&<SavedTheses items={savedTheses.filter(x=>(x.title+x.summary+x.foundation).toLowerCase().includes(query.toLowerCase()))} update={persistTheses}/>} 
 </section>
}

function Library({query,saveCitation}:{query:string;saveCitation:(a:string,b:string,c?:string)=>void}){const refs=[
 {title:"Código de Defesa do Consumidor",meta:"Lei nº 8.078/1990",tag:"Legislação",text:"Responsabilidade objetiva do fornecedor por defeitos relativos à prestação dos serviços.",source:"CDC · art. 14"},
 {title:"Código Brasileiro de Aeronáutica",meta:"Lei nº 7.565/1986",tag:"Legislação",text:"Regras especiais aplicáveis ao transporte aéreo e à responsabilidade do transportador.",source:"CBA"},
 {title:"Resolução ANAC nº 400",meta:"Condições gerais de transporte aéreo",tag:"Regulação",text:"Direitos do passageiro em casos de atraso, cancelamento, interrupção e preterição.",source:"ANAC · Resolução 400"},
 {title:"Tema 210 do STF",meta:"Convenções internacionais e transporte aéreo",tag:"Jurisprudência",text:"Prevalência das convenções internacionais nos limites dos danos materiais em transporte aéreo internacional.",source:"STF · Tema 210"}
 ].filter(x=>(x.title+x.meta+x.tag).toLowerCase().includes(query.toLowerCase()));return <div className="library-grid">{refs.map(x=><article key={x.title}><label>{x.tag}</label><h3>{x.title}</h3><small>{x.meta}</small><p>{x.text}</p><button onClick={()=>saveCitation(x.title,x.text,x.source)}><Highlighter/> Salvar como citação</button></article>)}</div>}

function SavedCitations({items,update}:{items:SavedCitation[];update:(x:SavedCitation[])=>void}){const [custom,setCustom]=useState(false);const [draft,setDraft]=useState({title:"",text:"",source:"",notes:""});const add=()=>{if(!draft.title.trim()||!draft.text.trim())return;update([...items,{...draft,id:crypto.randomUUID()}]);setDraft({title:"",text:"",source:"",notes:""});setCustom(false)};return <>{custom&&<div className="editor-card"><div><b>Nova citação</b><button onClick={()=>setCustom(false)}><X/></button></div><input placeholder="Título ou assunto" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><textarea placeholder="Cole aqui o trecho da jurisprudência" value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})}/><input placeholder="Tribunal, processo, relator ou fonte" value={draft.source} onChange={e=>setDraft({...draft,source:e.target.value})}/><button className="primary action-button" onClick={add}><Save/> Salvar citação</button></div>}<button className="outline-action" onClick={()=>setCustom(true)}><Plus/> Nova citação manual</button>{items.length?<div className="saved-list">{items.map(x=><article key={x.id}><div><label>Citação salva</label><button className="danger" onClick={()=>update(items.filter(y=>y.id!==x.id))}><Trash2/></button></div><h3>{x.title}</h3><blockquote>“{x.text}”</blockquote><small>{x.source||"Fonte não informada"}</small></article>)}</div>:<EmptyCollection icon={<Highlighter/>} title="Nenhuma citação salva" text="Salve trechos da análise, da biblioteca ou cadastre uma jurisprudência manualmente."/>}</>}

function SavedTheses({items,update}:{items:SavedThesis[];update:(x:SavedThesis[])=>void}){const [custom,setCustom]=useState(false);const [draft,setDraft]=useState({title:"",summary:"",foundation:""});const add=()=>{if(!draft.title.trim()||!draft.summary.trim())return;update([...items,{...draft,id:crypto.randomUUID()}]);setDraft({title:"",summary:"",foundation:""});setCustom(false)};return <>{custom&&<div className="editor-card"><div><b>Nova tese</b><button onClick={()=>setCustom(false)}><X/></button></div><input placeholder="Nome da tese" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><textarea placeholder="Estruture o argumento principal" value={draft.summary} onChange={e=>setDraft({...draft,summary:e.target.value})}/><input placeholder="Fundamento legal ou jurisprudencial" value={draft.foundation} onChange={e=>setDraft({...draft,foundation:e.target.value})}/><button className="primary action-button" onClick={add}><Save/> Salvar tese</button></div>}<button className="outline-action" onClick={()=>setCustom(true)}><Plus/> Nova tese manual</button>{items.length?<div className="saved-list thesis-bank">{items.map(x=><article key={x.id}><div><label>Tese jurídica</label><button className="danger" onClick={()=>update(items.filter(y=>y.id!==x.id))}><Trash2/></button></div><h3>{x.title}</h3><p>{x.summary}</p><small><Scale/> {x.foundation||"Fundamento a complementar"}</small></article>)}</div>:<EmptyCollection icon={<Scale/>} title="Seu banco de teses está vazio" text="Salve uma tese identificada na análise ou cadastre sua própria estrutura argumentativa."/>}</>}

function EmptyCollection({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="empty-collection"><i>{icon}</i><h3>{title}</h3><p>{text}</p></div>}

function ProfileModal({profile,close,save}:{profile:Profile;close:()=>void;save:(p:Profile)=>void}){const [draft,setDraft]=useState(profile);return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="profile-modal"><header><span><i>{initials(draft.name)}</i><div><small>Conta profissional</small><h2>Configurar perfil</h2></div></span><button onClick={close}><X/></button></header><label>Nome completo<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>E-mail<input type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><div className="profile-grid"><label>OAB<input placeholder="UF 000.000" value={draft.oab} onChange={e=>setDraft({...draft,oab:e.target.value})}/></label><label>Escritório<input placeholder="Nome do escritório" value={draft.office} onChange={e=>setDraft({...draft,office:e.target.value})}/></label></div><footer><button onClick={close}>Cancelar</button><button className="primary" onClick={()=>save(draft)}><Save/> Salvar perfil</button></footer></section></div>}

function Loading(){return <div className="loading"><i><Sparkles/></i><h2>Estruturando o documento</h2><p>Identificando partes, fatos, citações, teses, provas e riscos.</p><div><span/></div></div>}
function Empty({analyze,pick}:{analyze:()=>void,pick:()=>void}){return <div className="loading"><i><UploadCloud/></i><h2>Documento pronto para análise</h2><p>Inicie a leitura estruturada ou substitua o arquivo.</p><button onClick={pick}>Substituir</button> <button className="primary" onClick={analyze}><Sparkles/> Analisar documento</button></div>}
function Blocked({pick}:{pick:()=>void}){return <div className="loading blocked"><i><AlertTriangle/></i><h2>A análise automática ainda não está ativa</h2><p>O arquivo foi recebido, mas nenhuma informação foi extraída. Para evitar dados inventados, o AeroLex não exibirá o conteúdo demonstrativo como resultado do seu documento.</p><button onClick={pick}>Escolher outro arquivo</button></div>}
