"use client";
import { useEffect, useRef, useState } from "react";
import { AlertTriangle, BookOpen, Check, CheckCircle2, ChevronRight, CircleUserRound, Copy, Download, FileCheck2, FileText, FolderKanban, FolderOpen, Gavel, Highlighter, LayoutDashboard, Pencil, Plus, Save, Scale, Search, ShieldCheck, Sparkles, Trash2, UploadCloud, UserCog, Users, X } from "lucide-react";

type Tab = "visao"|"partes"|"citacoes"|"jurisprudencia"|"teses"|"provas"|"riscos";
type View = "analises"|"casos"|"documentos"|"biblioteca"|"jurisprudencia"|"citacoes-salvas"|"banco-teses";
type Jurisprudence={id:string;title:string;court:string;reference:string;excerpt:string;page:string;jusbrasilUrl?:string};
type LegalCase={id:string;title:string;client:string;opponent:string;caseNumber:string;status:"Ativo"|"Encerrado";deadline:string;deadlineStart?:string;deadlineDays?:number;deadlineBasis?:string;notes:string;documents:string[];updatedAt:string;sourceDocument?:string;sourceKey?:string;category?:string;summary?:string;facts?:unknown[];chronology?:unknown[];claims?:unknown[];theses?:unknown[];evidence?:unknown[];risks?:unknown[];jurisprudence?:unknown[]};
type SavedCitation={id:string;title:string;text:string;source:string;notes:string};
type SavedThesis={id:string;title:string;summary:string;foundation:string};
type Profile={name:string;email:string;oab:string;office:string};
const tabs:[Tab,string,number?][]=[["visao","Visão geral"],["partes","Partes",2],["citacoes","Citações",4],["jurisprudencia","Jurisprudência"],["teses","Teses",3],["provas","Provas",6],["riscos","Riscos",2]];
const seedJurisprudences:Jurisprudence[]=[
 {id:"tjpb-ap-0821902",title:"Cancelamento e atraso de voo - responsabilidade objetiva",court:"TJ-PB",reference:"Apelação Cível 0821902-13.2022.8.15.0001",excerpt:"Responsabilidade civil da companhia aérea é objetiva; cancelamento e atraso sem remanejamento ágil ou informações adequadas configuram falha na prestação do serviço.",page:"2-3",jusbrasilUrl:"https://www.jusbrasil.com.br/jurisprudencia/busca?q=TJ-PB+0821902-13.2022.8.15.0001"},
 {id:"tjsp-ap-1004409",title:"Precedente citado no acórdão do TJ-PB",court:"TJ-SP",reference:"Apelação 1004409-71.2018.8.26.0066",excerpt:"Precedente listado como jurisprudência relevante no acórdão transcrito pela petição.",page:"2",jusbrasilUrl:"https://www.jusbrasil.com.br/jurisprudencia/busca?q=TJSP+1004409-71.2018.8.26.0066"},
 {id:"tjsp-ap-1054634",title:"Precedente citado no acórdão do TJ-PB",court:"TJ-SP",reference:"Apelação 1054634-90.2018.8.26.0100",excerpt:"Precedente listado como jurisprudência relevante no acórdão transcrito pela petição.",page:"2",jusbrasilUrl:"https://www.jusbrasil.com.br/jurisprudencia/busca?q=TJSP+1054634-90.2018.8.26.0100"},
 {id:"stj-resp-1728068",title:"Precedente citado no acórdão do TJ-PB",court:"STJ",reference:"REsp 1.728.068/SP",excerpt:"Recurso especial listado como jurisprudência relevante no acórdão transcrito.",page:"2",jusbrasilUrl:"https://www.jusbrasil.com.br/jurisprudencia/busca?q=STJ+REsp+1728068%2FSP"},
 {id:"stf-are-1560244",title:"Repercussão geral sobre cancelamento, alteração e atraso de voo",court:"STF",reference:"ARE 1.560.244/RJ",excerpt:"Repercussão geral reconhecida para definir o regime jurídico da responsabilidade do transportador aéreo por cancelamento, alteração ou atraso decorrente de caso fortuito ou força maior.",page:"3-4",jusbrasilUrl:"https://www.jusbrasil.com.br/jurisprudencia/stf/4645395787"},
 {id:"stf-ai-762184",title:"Precedente constitucional citado no ARE 1.560.244",court:"STF",reference:"AI 762.184",excerpt:"Precedente citado no acórdão do ARE 1.560.244 em matéria de transporte aéreo e art. 178 da Constituição.",page:"4",jusbrasilUrl:"https://www.jusbrasil.com.br/jurisprudencia/busca?q=STF+AI+762.184"},
 {id:"stf-re-636331",title:"Tema 210 - transporte aéreo internacional",court:"STF",reference:"RE 636.331/RJ · Tema 210",excerpt:"Prevalência das normas e tratados internacionais limitadores da responsabilidade das transportadoras aéreas quanto a danos materiais em transporte internacional.",page:"4",jusbrasilUrl:"https://www.jusbrasil.com.br/jurisprudencia/busca?q=re+636331"},
 {id:"stf-re-1520841",title:"Transporte aéreo internacional de carga - repercussão geral",court:"STF",reference:"RE 1.520.841/SP",excerpt:"Precedente citado no ARE 1.560.244 sobre interpretação do art. 178 da Constituição em transporte aéreo internacional.",page:"4",jusbrasilUrl:"https://www.jusbrasil.com.br/jurisprudencia/stf/6122786525"},
 {id:"tjpr-ri-0013242",title:"Atraso superior a 20 horas e assistência deficiente",court:"TJ-PR",reference:"TJ-PR 00132426820238160173",excerpt:"Atraso prolongado, ausência de assistência suficiente e despesas extraordinárias fundamentam responsabilidade por danos materiais e morais.",page:"4-5",jusbrasilUrl:"https://www.jusbrasil.com.br/jurisprudencia/busca?q=TJ-PR+00132426820238160173"},
 {id:"tjpr-ap-0053765",title:"Precedente citado no acórdão do TJ-PR",court:"TJ-PR",reference:"0053765-35.2019.8.16.0021",excerpt:"Precedente listado como jurisprudência relevante no acórdão transcrito.",page:"5",jusbrasilUrl:"https://www.jusbrasil.com.br/jurisprudencia/busca?q=TJPR+0053765-35.2019.8.16.0021"},
 {id:"stj-resp-1796716",title:"Cancelamento de voo doméstico e dano moral",court:"STJ",reference:"REsp 1.796.716/MG",excerpt:"Recurso especial citado na petição em discussão sobre cancelamento de voo doméstico e configuração do dano moral conforme as circunstâncias concretas.",page:"5-6",jusbrasilUrl:"https://www.jusbrasil.com.br/jurisprudencia/busca?q=resp+1.796.716"},
 {id:"stj-resp-1281090",title:"Precedente citado pelo TJ-MT",court:"STJ",reference:"REsp 1.281.090/SP",excerpt:"Precedente listado no acórdão do TJ-MT transcrito pela petição.",page:"6",jusbrasilUrl:"https://www.jusbrasil.com.br/jurisprudencia/busca?q=STJ+REsp+1.281.090%2FSP"},
 {id:"stj-resp-974138",title:"Precedente citado pelo TJ-MT",court:"STJ",reference:"REsp 974.138/SP",excerpt:"Precedente listado no acórdão do TJ-MT transcrito pela petição.",page:"6",jusbrasilUrl:"https://www.jusbrasil.com.br/jurisprudencia/busca?q=STJ+REsp+974.138%2FSP"},
 {id:"stj-resp-1807242",title:"Precedente citado pelo TJ-MT",court:"STJ",reference:"REsp 1.807.242/RS",excerpt:"Precedente listado no acórdão do TJ-MT transcrito pela petição.",page:"6",jusbrasilUrl:"https://www.jusbrasil.com.br/jurisprudencia/busca?q=STJ+REsp+1.807.242%2FRS"},
 {id:"tjmt-1010931",title:"Precedente da Turma Recursal citado no acórdão",court:"TJ-MT",reference:"1010931-59.2023.8.11.0001",excerpt:"Precedente listado como jurisprudência relevante no acórdão do TJ-MT.",page:"6",jusbrasilUrl:"https://www.jusbrasil.com.br/jurisprudencia/busca?q=TJMT+1010931-59.2023.8.11.0001"},
 {id:"tjmt-1007914",title:"Precedente da Turma Recursal citado no acórdão",court:"TJ-MT",reference:"1007914-15.2023.8.11.0001",excerpt:"Precedente listado como jurisprudência relevante no acórdão do TJ-MT.",page:"6",jusbrasilUrl:"https://www.jusbrasil.com.br/jurisprudencia/busca?q=TJMT+1007914-15.2023.8.11.0001"},
 {id:"tjmt-ri-1019114",title:"Voo doméstico, manutenção não programada e dano moral",court:"TJ-MT",reference:"Recurso Inominado 10191141420268110001",excerpt:"Atraso de aproximadamente 15 horas, perda de conexão e circunstâncias concretas podem ultrapassar o mero aborrecimento e caracterizar dano moral.",page:"5-6",jusbrasilUrl:"https://www.jusbrasil.com.br/jurisprudencia/busca?q=TJ-MT+10191141420268110001"}
];
const SUPABASE_URL="https://wefovgbdapaanqqgqapp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_3YTteOF_JIbTVbQcA6vEgQ_PZwBjoxW";
const jusbrasilSearchUrl=(j:Jurisprudence)=>j.jusbrasilUrl||`https://www.jusbrasil.com.br/jurisprudencia/busca?q=${encodeURIComponent([j.court,j.reference,j.title].filter(Boolean).join(" "))}`;
const parties=[["Parte autora","Felipe Augusto Nunes","Autor · administrador · qualificação no preâmbulo, página 1","FN"],["Parte ré","Companhia Aérea Brasil S.A.","Transportadora aérea · qualificação no preâmbulo, página 1","CA"]];
const citations=[
 ["1","Cancelamento e reacomodação tardia","O Autor somente foi reacomodado em voo do dia seguinte, chegando a Porto Alegre em 15 de setembro de 2026, às 17h35, aproximadamente 29 horas e 30 minutos após o horário originalmente previsto.","Delimita a extensão temporal do atraso decorrente do cancelamento."],
 ["1","Despesas emergenciais","Durante o período de espera, o Autor permaneceu no aeroporto por várias horas e precisou custear hospedagem, alimentação e transporte, no total de R$ 1.936,40.","Relaciona a ausência de assistência ao dano material alegado."],
 ["1","Consequência profissional","O atraso também ocasionou a perda de reunião profissional previamente agendada para a tarde de 14 de setembro de 2026.","Individualiza consequência concreta invocada no pedido de dano moral."],
 ["6","Dano moral no caso concreto","No caso concreto, o atraso de aproximadamente 29 horas e 30 minutos, associado à perda da reunião profissional e às despesas emergenciais, atingiu a tranquilidade, a organização pessoal e a esfera de dignidade do Autor.","Sintetiza as circunstâncias concretas usadas para fundamentar o pedido moral."]
];
const theses=[
 ["Forte","Responsabilidade objetiva e falha do serviço","A inicial associa cancelamento do voo, reacomodação apenas no dia seguinte, falta de informação e assistência material insuficiente.","Páginas 1-3 · CDC, art. 14"],
 ["Forte","Ressarcimento dos danos materiais","É pedido o ressarcimento integral de R$ 1.936,40 por hospedagem, alimentação e transporte suportados durante a espera.","Páginas 1 e 4-5 · pedido d, página 7"],
 ["Moderada","Dano moral pelas circunstâncias concretas","O pedido de R$ 15.000,00 se apoia no atraso aproximado de 29h30, perda de reunião profissional e ausência de assistência adequada.","Páginas 5-7 · pedido e"]
];

export default function Home(){
 const input=useRef<HTMLInputElement>(null); const [file,setFile]=useState("Peca Direito da Aviacao (58adec9f-0af5-49b7-8eb0-e4168705633f).pdf"); const [originalFile,setOriginalFile]=useState<File|null>(null); const [tab,setTab]=useState<Tab>("visao"); const [done,setDone]=useState(true); const [loading,setLoading]=useState(false); const [blocked,setBlocked]=useState(false); const [copied,setCopied]=useState("");
 const [view,setView]=useState<View>("analises");
 const [savedCitations,setSavedCitations]=useState<SavedCitation[]>([]);
 const [savedTheses,setSavedTheses]=useState<SavedThesis[]>([]);
 const [cases,setCases]=useState<LegalCase[]>([]);
 const [jurisprudences,setJurisprudences]=useState<Jurisprudence[]>(seedJurisprudences);
 const [profile,setProfile]=useState<Profile>({name:"Rafael Andrade",email:"rafaelleao2001@gmail.com",oab:"",office:""});
 const [profileOpen,setProfileOpen]=useState(false); const [toast,setToast]=useState("");
 const mapCase=(r:any):LegalCase=>({id:r.id,title:r.title||"Caso sem título",client:r.client||"",opponent:r.opponent||"",caseNumber:r.case_number||"",status:r.status||"Ativo",deadline:r.deadline||"",deadlineStart:r.deadline_start||"",deadlineDays:r.deadline_days||undefined,deadlineBasis:r.deadline_basis||"CPC",notes:r.notes||"",documents:Array.isArray(r.documents)?r.documents:[],updatedAt:r.updated_at?new Date(r.updated_at).toLocaleDateString("pt-BR"):"",sourceDocument:r.source_document||undefined,sourceKey:r.source_key||undefined,category:r.category||undefined,summary:r.summary||undefined,facts:r.facts||[],chronology:r.chronology||[],claims:r.claims||[],theses:r.theses||[],evidence:r.evidence||[],risks:r.risks||[],jurisprudence:r.jurisprudence||[]});
 const loadCases=()=>fetch("/api/cases",{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then((rows:unknown)=>{if(Array.isArray(rows))setCases(rows.map(mapCase))}).catch(()=>{});
 useEffect(()=>{try{const c=localStorage.getItem("aerolex-citations"),t=localStorage.getItem("aerolex-theses"),p=localStorage.getItem("aerolex-profile");if(c)setSavedCitations(JSON.parse(c));if(t)setSavedTheses(JSON.parse(t));if(p)setProfile(JSON.parse(p))}catch{}
  loadCases();
  fetch(`${SUPABASE_URL}/rest/v1/aerolex_jurisprudence?select=id,title,court,reference,excerpt,page,jusbrasil_url&order=created_at.asc`,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${SUPABASE_PUBLISHABLE_KEY}`}})
   .then(r=>r.ok?r.json():Promise.reject(new Error("Supabase indisponível")))
   .then((rows:unknown)=>{if(Array.isArray(rows)&&rows.length)setJurisprudences(rows.map((r:any)=>({id:r.id,title:r.title,court:r.court,reference:r.reference,excerpt:r.excerpt,page:r.page,jusbrasilUrl:r.jusbrasil_url||undefined})))})
   .catch(()=>{});
 },[]);

 const persistCitations=(items:SavedCitation[])=>{setSavedCitations(items);localStorage.setItem("aerolex-citations",JSON.stringify(items))};
 const persistTheses=(items:SavedThesis[])=>{setSavedTheses(items);localStorage.setItem("aerolex-theses",JSON.stringify(items))};
 const persistCases=async(items:LegalCase[])=>{setCases(items)};
 const notify=(message:string)=>{setToast(message);setTimeout(()=>setToast(""),1800)};
 const saveCitation=(title:string,text:string,source="Documento analisado")=>{if(savedCitations.some(x=>x.text===text)){notify("Esta citação já está salva");return}persistCitations([...savedCitations,{id:crypto.randomUUID(),title,text,source,notes:""}]);notify("Citação salva")};
 const saveThesis=(title:string,summary:string,foundation:string)=>{if(savedTheses.some(x=>x.title===title)){notify("Esta tese já está no banco");return}persistTheses([...savedTheses,{id:crypto.randomUUID(),title,summary,foundation}]);notify("Tese adicionada ao banco")};
 const runAutoAnalysis=async(f:File)=>{setFile(f.name);setOriginalFile(f);setDone(false);setBlocked(false);setLoading(true);setTab("visao");try{const form=new FormData();form.append("file",f);const response=await fetch("/api/analyze",{method:"POST",body:form});const result=(await response.json().catch(()=>({}))) as {detail?:string;error?:string};if(!response.ok)throw new Error(result.detail||result.error||"Falha ao analisar o documento.");await loadCases();setLoading(false);setOriginalFile(null);setView("casos");notify("Caso estruturado e salvo automaticamente");}catch(error){setLoading(false);setBlocked(true);notify(error instanceof Error?error.message:"Falha na análise automática")}};
 const pick=(f?:File)=>{if(f)void runAutoAnalysis(f)};
 const analyze=()=>{if(originalFile)void runAutoAnalysis(originalFile)};
 const copy=(id:string,text:string)=>{navigator.clipboard?.writeText(text);setCopied(id);setTimeout(()=>setCopied(""),1200)};
 const downloadBlob=(blob:Blob,name:string)=>{const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download=name;a.target="_blank";a.rel="noopener";document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(u),30000)};
 const exportFile=()=>{const text=`AEROLEX — ANÁLISE JURÍDICA\r\nDocumento: ${file}\r\n\r\nPARTES\r\n${parties.map(p=>p[0]+": "+p[1]).join("\r\n")}\r\n\r\nCITAÇÕES\r\n${citations.map(c=>"Página "+c[0]+': “'+c[2]+'”').join("\r\n\r\n")}\r\n\r\nTESES\r\n${theses.map(t=>t[1]+": "+t[2]).join("\r\n\r\n")}\r\n\r\nRevisão humana obrigatória.`;downloadBlob(new Blob(["\\ufeff",text],{type:"text/plain;charset=utf-8"}),"analise-aerolex.txt")};
 const downloadOriginal=()=>{if(originalFile){downloadBlob(originalFile,originalFile.name);return}const a=document.createElement("a");a.href="/documento-original.pdf";a.download="peticao-inicial-original.pdf";document.body.appendChild(a);a.click();a.remove()};
 const downloadAnnotated=()=>{const a=document.createElement("a");a.href="/documento-analisado-marcado.pdf";a.download="peticao-inicial-analisada-aerolex.pdf";document.body.appendChild(a);a.click();a.remove()};
 return <main className="shell">
  <header><div className="brand"><img src="/aeroveritas-logo.png" width="1935" height="360" alt="AeroVeritas — Inteligência Jurídica"/></div><button className="search" onClick={()=>setView("casos")}><Search size={15}/> Buscar casos <kbd>⌘ K</kbd></button><button className="circle profile-button" onClick={()=>setProfileOpen(true)} title="Configurar perfil"><span>{initials(profile.name)}</span></button></header>
  <aside><button className="new" onClick={()=>{setView("analises");input.current?.click()}}><Plus size={16}/> Nova análise</button><nav><label>Espaço de trabalho</label><Nav active={view==="analises"} onClick={()=>setView("analises")} icon={<LayoutDashboard size={16}/>} label="Análises"/><Nav active={view==="casos"} onClick={()=>setView("casos")} icon={<FolderKanban size={16}/>} label="Casos" count={cases.length}/><Nav active={view==="biblioteca"} onClick={()=>setView("biblioteca")} icon={<BookOpen size={16}/>} label="Biblioteca jurídica"/><Nav active={view==="jurisprudencia"} onClick={()=>setView("jurisprudencia")} icon={<Gavel size={16}/>} label="Jurisprudência" count={jurisprudences.length}/><label>Ferramentas</label><Nav active={view==="citacoes-salvas"} onClick={()=>setView("citacoes-salvas")} icon={<Highlighter size={16}/>} label="Citações salvas" count={savedCitations.length}/><Nav active={view==="banco-teses"} onClick={()=>setView("banco-teses")} icon={<Scale size={16}/>} label="Banco de teses" count={savedTheses.length}/></nav><div className="privacy"><ShieldCheck size={18}/><span><strong>Ambiente confidencial</strong><small>Revise a análise antes do uso profissional.</small></span></div></aside>
  <input ref={input} type="file" accept=".pdf" hidden onChange={e=>pick(e.target.files?.[0])}/>
  {view==="analises"?<section className="workspace">
   <div className="title"><div><p>Análises <ChevronRight size={12}/> Documento aéreo</p><h1>Leitura jurídica do documento</h1><span>Extração estruturada com rastreabilidade até o trecho original.</span></div><button onClick={exportFile} disabled={!done||!!originalFile}><Download size={15}/> Exportar análise</button></div>
   <div className="file"><i><FileText size={23}/></i><span><strong>{file}</strong><small>{originalFile?"PDF recebido · estruturação automática em andamento":"7 páginas · análise extraída e revisada"}</small></span><em className={done&&!originalFile?"ok":""}>{done&&!originalFile?<CheckCircle2 size={14}/>:<UploadCloud size={14}/>} {done&&!originalFile?"Análise validada":"Estruturação automática"}</em><button onClick={()=>input.current?.click()}>Substituir</button>{originalFile&&!blocked&&<button className="primary" onClick={analyze}><Sparkles size={15}/> Analisar</button>}</div>
   {loading?<Loading/>:blocked?<Blocked pick={()=>input.current?.click()}/>:done&&!originalFile?<><div className="tabs">{tabs.map(t=><button className={tab===t[0]?"on":""} onClick={()=>setTab(t[0])} key={t[0]}>{t[1]} {t[2]&&<b>{t[2]}</b>}</button>)}</div><div className="grid"><article className="panel">{tab==="visao"&&<Overview setTab={setTab}/>} {tab==="partes"&&<Parties/>} {tab==="citacoes"&&<Citations copy={copy} copied={copied} save={saveCitation}/>} {tab==="jurisprudencia"&&<JurisprudencePanel items={jurisprudences}/>} {tab==="teses"&&<Theses save={saveThesis}/>} {tab==="provas"&&<Evidence/>} {tab==="riscos"&&<Risks/>}</article><Source/></div></>:<Empty analyze={analyze} pick={()=>input.current?.click()}/>} 
  </section>:<SectionView view={view} file={file} setView={setView} savedCitations={savedCitations} persistCitations={persistCitations} savedTheses={savedTheses} persistTheses={persistTheses} saveCitation={saveCitation} input={input} cases={cases} persistCases={persistCases} jurisprudences={jurisprudences}/>} 
  {profileOpen&&<ProfileModal profile={profile} close={()=>setProfileOpen(false)} save={p=>{setProfile(p);localStorage.setItem("aerolex-profile",JSON.stringify(p));setProfileOpen(false);notify("Perfil atualizado")}}/>}
  {toast&&<div className="toast"><CheckCircle2/> {toast}</div>}
  <footer className="ai-responsibility-notice"><AlertTriangle/><span><strong>Aviso sobre uso de Inteligência Artificial</strong><small>Sistemas de Inteligência Artificial podem cometer erros, apresentar informações imprecisas ou interpretar incorretamente documentos e fontes. Verifique sempre as informações, citações, jurisprudência, legislação, prazos e demais conteúdos antes de utilizá-los. Toda informação utilizada em petições, pareceres, contratos, manifestações processuais ou quaisquer outras peças jurídicas é de exclusiva responsabilidade do usuário.</small></span></footer>
 </main>
}

function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"U"}
function Nav({active,onClick,icon,label,count}:{active:boolean;onClick:()=>void;icon:React.ReactNode;label:string;count?:number}){return <button className={active?"nav-item on":"nav-item"} onClick={onClick}>{icon}<span>{label}</span>{count!==undefined&&count>0?<b>{count}</b>:null}</button>}

function Head({over,title}:{over:string,title:string}){return <div className="head"><small>{over}</small><h2>{title}</h2></div>}
function Overview({setTab}:{setTab:(t:Tab)=>void}){return <><Head over="Síntese da análise" title="Cancelamento de voo com atraso de aproximadamente 29h30"/><p className="lead">Felipe Augusto Nunes ajuíza ação indenizatória contra Companhia Aérea Brasil S.A. A petição relata cancelamento do voo Recife-Porto Alegre por alegado problema operacional, reacomodação somente no dia seguinte, chegada cerca de 29 horas e 30 minutos após o previsto, assistência material insuficiente, despesas de R$ 1.936,40 e perda de reunião profissional.</p><div className="metrics"><button onClick={()=>setTab("partes")}><Users/> <span><b>2</b> partes identificadas</span></button><button onClick={()=>setTab("citacoes")}><Highlighter/> <span><b>4</b> trechos citáveis</span></button><button onClick={()=>setTab("teses")}><Scale/> <span><b>3</b> teses principais</span></button></div><hr/><Head over="Cronologia extraída" title="Sequência dos fatos"/><div className="timeline"><p><small>14 SET 2026 · 07h10</small><b>Embarque previsto</b><span>Trecho Recife-PE para Porto Alegre-RS, com chegada originalmente prevista para 12h05.</span></p><p><small>14 SET 2026</small><b>Cancelamento por alegado problema operacional</b><span>Após o check-in, o Autor foi informado do cancelamento e afirma não ter recebido solução imediata nem informação clara sobre a reacomodação.</span></p><p><small>15 SET 2026 · 17h35</small><b>Chegada ao destino final</b><span>Reacomodação apenas no dia seguinte, aproximadamente 29 horas e 30 minutos após o horário originalmente previsto.</span></p></div><div className="warning"><AlertTriangle/><span><b>Ponto que exige confirmação</b><small>A peça afirma que bilhete, comprovante de compra, despesas e outros documentos estão anexos, mas o PDF recebido contém somente a petição de 7 páginas.</small></span></div></>}
function Parties(){return <><Head over="Sujeitos da relação" title="Partes identificadas"/><div className="cards parties">{parties.map((p,i)=><section key={p[1]}><i className={i?"dark":""}>{p[3]}</i><span><small>{p[0]}</small><b>{p[1]}</b><em>{p[2]}</em></span><label><CheckCircle2/> Alta confiança</label></section>)}</div><div className="notice"><FileCheck2/><span><b>Critério de identificação</b><small>Nomes e papéis processuais localizados exclusivamente no preâmbulo da petição.</small></span></div></>}
function Citations({copy,copied,save}:{copy:(a:string,b:string)=>void;copied:string;save:(a:string,b:string,c?:string)=>void}){return <><Head over="Trechos rastreáveis" title="Citações relevantes"/><p className="intro">Copie um trecho ou salve-o na sua coleção para reutilizar em outras peças.</p><div className="cards citations">{citations.map(c=><section key={c[1]}><div><small>Página {c[0]}</small><span className="card-actions"><button onClick={()=>save(c[1],c[2],`Petição inicial · página ${c[0]}`)}><Save/> Salvar</button><button onClick={()=>copy(c[1],c[2])}>{copied===c[1]?<Check/>:<Copy/>} {copied===c[1]?"Copiado":"Copiar"}</button></span></div><b>{c[1]}</b><blockquote>“{c[2]}”</blockquote><p><strong>Utilidade:</strong> {c[3]}</p></section>)}</div></>}
function JusbrasilSource({item}:{item:Jurisprudence}){return <a className="jusbrasil-source" href={jusbrasilSearchUrl(item)} target="_blank" rel="noopener noreferrer" aria-label={`Abrir fonte de ${item.reference} no Jusbrasil`} title={`Abrir ${item.reference} no Jusbrasil`}><img src="/jusbrasil-logo.png" width="560" height="110" alt="Jusbrasil"/></a>}

function JurisprudencePanel({items}:{items:Jurisprudence[]}){return <><Head over="Precedentes citados" title="Jurisprudência identificada na petição"/><p className="intro">As referências abaixo são exibidas somente quando constam do documento analisado. Clique na logo do Jusbrasil para abrir a referência correspondente ou pesquisar o número do processo.</p>{items.length?<div className="saved-list jurisprudence-list">{items.map(j=><article key={j.id}><div><label>{j.court}{j.page?` · página ${j.page}`:""}</label><JusbrasilSource item={j}/></div><h3>{j.title}</h3><small>{j.reference}</small>{j.excerpt&&<blockquote>“{j.excerpt}”</blockquote>}</article>)}</div>:<EmptyCollection icon={<Gavel/>} title="Nenhuma jurisprudência identificada" text="A petição atual não possui referência jurisprudencial estruturada na análise disponível. O AeroLex não cria precedentes inexistentes."/>}</>}

function JurisprudenceLibrary({items,query}:{items:Jurisprudence[];query:string}){const filtered=items.filter(j=>(j.title+j.court+j.reference+j.excerpt).toLowerCase().includes(query.toLowerCase()));return filtered.length?<div className="saved-list jurisprudence-list">{filtered.map(j=><article key={j.id}><div><label>{j.court}{j.page?` · página ${j.page}`:""}</label><JusbrasilSource item={j}/></div><h3>{j.title}</h3><p>{j.reference}</p>{j.excerpt&&<blockquote>“{j.excerpt}”</blockquote>}</article>)}</div>:<EmptyCollection icon={<Gavel/>} title="Nenhuma jurisprudência encontrada" text={items.length?"Nenhum precedente corresponde à busca.":"Nenhuma jurisprudência foi identificada nos documentos analisados até agora."}/>} 

function Theses({save}:{save:(a:string,b:string,c:string)=>void}){return <><Head over="Construção argumentativa" title="Principais teses identificadas"/><p className="intro">Revise a hipótese e salve-a no banco para reaproveitar sua estrutura.</p><div className="cards theses">{theses.map((t,i)=><section key={t[1]}><i>0{i+1}</i><span><div><b>{t[1]}</b><span className="thesis-tools"><label className={t[0]==="Forte"?"green":""}>{t[0]}</label><button onClick={()=>save(t[1],t[2],t[3])}><Save/> Salvar</button></span></div><p>{t[2]}</p><small><FileCheck2/> Base documental: {t[3]}</small></span></section>)}</div></>}
function Evidence(){const e=[["Passagem e itinerário","A petição afirma que o Autor apresenta bilhete e comprovante de compra","Mencionado"],["Registros do cancelamento e reacomodação","Indicados na inicial e também requeridos à companhia aérea","Mencionado"],["Comprovantes de R$ 1.936,40","Despesas de hospedagem, alimentação e transporte alegadas como anexas","Mencionado"],["Protocolo 2026-0915-8390","Reclamação administrativa e pedido de reembolso narrados na página 1","Mencionado"],["Prova da reunião profissional","A perda da reunião é narrada, mas não há documento correspondente no PDF recebido","Ausente"],["Anexos comprobatórios","Não integram o PDF recebido","Ausente"]];return <><Head over="Matriz documental" title="Provas mencionadas e ausentes"/><div className="evidence">{e.map(x=><p key={x[0]}><FileText/><span><b>{x[0]}</b><small>{x[1]}</small></span><em className={x[2]==="Ausente"?"miss":""}>{x[2]}</em></p>)}</div></>}
function Risks(){return <><Head over="Revisão crítica" title="Riscos e pontos de atenção"/><div className="cards risks"><section><AlertTriangle/><span><small>Risco probatório</small><b>Causa concreta do cancelamento depende de prova da companhia</b><p>A inicial registra apenas a alegação de problema operacional e requer histórico do voo, justificativa do cancelamento, comunicações, registros de reacomodação e assistência.</p></span></section><section><AlertTriangle/><span><small>Documentação não conferida</small><b>Comprovantes mencionados não constam do PDF</b><p>Os R$ 1.936,40, o bilhete, a reacomodação e a reunião profissional dependem da conferência dos documentos anexos mencionados na petição.</p></span></section></div></>}
function Source(){return <aside className="source"><div className="source-head"><span><b>Documento analisado</b><small>7 páginas · arquivo atual conferido</small></span></div><a className="document-thumbnail" href="/documento-original.pdf" target="_blank" rel="noopener noreferrer" title="Abrir documento original"><img src="/documento-miniatura.png?v=4" alt="Miniatura da primeira página do documento analisado"/><span><FileText/> Abrir documento</span></a><div className="document-downloads"><a href="/documento-original.pdf" download><Download/> Baixar original</a><a href="/documento-analisado-marcado.pdf" download><Highlighter/> Baixar versão marcada</a></div><div className="mark-legend"><span><i className="mark thesis"/> Teses</span><span><i className="mark evidence-mark"/> Provas</span><span><i className="mark quote-mark"/> Citações</span></div><small><ShieldCheck/> O original e a versão marcada estão disponíveis para download neste deploy.</small></aside>}

function SectionView({view,file,setView,savedCitations,persistCitations,savedTheses,persistTheses,saveCitation,input,cases,persistCases,jurisprudences}:{view:View;file:string;setView:(v:View)=>void;savedCitations:SavedCitation[];persistCitations:(x:SavedCitation[])=>void;savedTheses:SavedThesis[];persistTheses:(x:SavedThesis[])=>void;saveCitation:(a:string,b:string,c?:string)=>void;input:React.RefObject<HTMLInputElement|null>;cases:LegalCase[];persistCases:(x:LegalCase[])=>void;jurisprudences:Jurisprudence[]}){
 const [query,setQuery]=useState("");
 const titles:Record<Exclude<View,"analises">,[string,string]>={casos:["Casos","Organize clientes, processos, prazos, documentos e anotações em um só lugar."],documentos:["Documentos","Arquivos enviados e vinculados às suas análises."],biblioteca:["Biblioteca jurídica","Referências essenciais para pesquisa em Direito Aéreo."],jurisprudencia:["Jurisprudência","Precedentes citados nos documentos analisados, com acesso à fonte no Jusbrasil."],"citacoes-salvas":["Citações salvas","Trechos de jurisprudência e documentos para reutilização."],"banco-teses":["Banco de teses","Argumentos jurídicos organizados para suas próximas peças."]};
 const [title,subtitle]=titles[view as Exclude<View,"analises">];
 return <section className="workspace section-page"><div className="section-title"><div><small>Espaço de trabalho</small><h1>{title}</h1><p>{subtitle}</p></div>{view==="documentos"&&<button className="primary action-button" onClick={()=>input.current?.click()}><Plus/> Adicionar documento</button>}</div>
  <div className="section-toolbar"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Buscar em ${title.toLowerCase()}`}/></div>
  {view==="casos"&&<Cases items={cases} update={persistCases} currentFile={file}/>} 
  {view==="documentos"&&<div className="document-table"><div className="table-head"><span>Documento</span><span>Status</span><span>Tipo</span><span></span></div><div className="table-row"><i><FileText/></i><span><b>{file}</b><small>Adicionado hoje · 7 páginas</small></span><em>Análise validada</em><small>Petição inicial</small><button onClick={()=>setView("analises")}>Abrir <ChevronRight/></button></div></div>}
  {view==="biblioteca"&&<Library query={query} saveCitation={saveCitation}/>} 
  {view==="jurisprudencia"&&<JurisprudenceLibrary items={jurisprudences} query={query}/>} 
  {view==="citacoes-salvas"&&<SavedCitations items={savedCitations.filter(x=>(x.title+x.text+x.source).toLowerCase().includes(query.toLowerCase()))} update={persistCitations}/>} 
  {view==="banco-teses"&&<SavedTheses items={savedTheses.filter(x=>(x.title+x.summary+x.foundation).toLowerCase().includes(query.toLowerCase()))} update={persistTheses}/>} 
 </section>
}


function caseItemText(item:unknown){
 if(typeof item==="string")return item;
 if(!item||typeof item!=="object")return String(item??"");
 const o=item as Record<string,unknown>;
 const preferred=["date","event","title","text","summary","detail","foundation","value","status","reference","court","page"];
 return preferred.filter(k=>o[k]!==undefined&&o[k]!==null&&String(o[k]).trim()).map(k=>String(o[k])).join(" · ")||JSON.stringify(o);
}
function CaseDataSection({title,items}:{title:string;items?:unknown[]}){
 if(!Array.isArray(items)||!items.length)return null;
 return <section className="case-detail-section"><h4>{title}<b>{items.length}</b></h4><div>{items.map((item,i)=><p key={title+"-"+i}>{caseItemText(item)}</p>)}</div></section>
}

function Cases({items,update,currentFile}:{items:LegalCase[];update:(x:LegalCase[])=>void;currentFile:string}){
 const [editing,setEditing]=useState<LegalCase|null>(null);
 const [filter,setFilter]=useState<"Todos"|"Ativo"|"Encerrado">("Todos");
 const [expandedId,setExpandedId]=useState<string|null>(null);
 const [deletingId,setDeletingId]=useState<string|null>(null);
 const blank=():LegalCase=>({id:"temp-"+crypto.randomUUID(),title:"",client:"",opponent:"",caseNumber:"",status:"Ativo",deadline:"",deadlineStart:"",deadlineDays:undefined,deadlineBasis:"CPC",notes:"",documents:[],updatedAt:new Date().toLocaleDateString("pt-BR"),category:"Direito Aéreo"});
 const visible=filter==="Todos"?items:items.filter(x=>x.status===filter);
 const save=async(c:LegalCase)=>{if(!c.title.trim()&&!c.client.trim())return;const exists=items.some(x=>x.id===c.id)&&!c.id.startsWith("temp-");const payload={...c,id:exists?c.id:undefined};const response=await fetch("/api/cases",{method:exists?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!response.ok)return;const rows=await response.json().catch(()=>[]);const r=Array.isArray(rows)?rows[0]:null;if(r){const mapped:LegalCase={id:r.id,title:r.title||c.title,client:r.client||"",opponent:r.opponent||"",caseNumber:r.case_number||"",status:r.status||"Ativo",deadline:r.deadline||"",deadlineStart:r.deadline_start||"",deadlineDays:r.deadline_days||undefined,deadlineBasis:r.deadline_basis||"CPC",notes:r.notes||"",documents:Array.isArray(r.documents)?r.documents:[],updatedAt:r.updated_at?new Date(r.updated_at).toLocaleDateString("pt-BR"):new Date().toLocaleDateString("pt-BR"),sourceDocument:r.source_document||undefined,sourceKey:r.source_key||undefined,category:r.category||undefined,summary:r.summary||undefined,facts:r.facts||[],chronology:r.chronology||[],claims:r.claims||[],theses:r.theses||[],evidence:r.evidence||[],risks:r.risks||[],jurisprudence:r.jurisprudence||[]};update(exists?items.map(x=>x.id===c.id?mapped:x):[mapped,...items])}setEditing(null)};
 const remove=async(id:string)=>{if(!window.confirm("Excluir este caso? Esta ação não pode ser desfeita."))return;setDeletingId(id);try{const response=await fetch("/api/cases?id="+encodeURIComponent(id),{method:"DELETE"});if(response.ok){update(items.filter(x=>x.id!==id));if(expandedId===id)setExpandedId(null)}}finally{setDeletingId(null)}};
 return <div className="cases-wrap">
  <div className="cases-toolbar"><div className="case-filters">{(["Todos","Ativo","Encerrado"] as const).map(x=><button key={x} className={filter===x?"on":""} onClick={()=>setFilter(x)}>{x}<b>{x==="Todos"?items.length:items.filter(c=>c.status===x).length}</b></button>)}</div><button className="primary action-button" onClick={()=>setEditing(blank())}><Plus/> Novo caso</button></div>
  <div className="cases-summary"><span><b>{items.length}</b><small>casos salvos</small></span><span><b>{items.filter(x=>x.status==="Ativo").length}</b><small>ativos</small></span><span><b>{items.filter(x=>x.deadline).length}</b><small>com prazo</small></span><span><b>{items.reduce((n,x)=>n+(x.documents?.length||0),0)}</b><small>documentos vinculados</small></span></div>
  {editing&&<div className="editor-card case-editor"><div><b>{items.some(x=>x.id===editing.id)?"Editar caso":"Novo caso"}</b><button onClick={()=>setEditing(null)}><X/></button></div><input placeholder="Título do caso" value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/><div className="case-fields"><input placeholder="Cliente" value={editing.client} onChange={e=>setEditing({...editing,client:e.target.value})}/><input placeholder="Parte contrária" value={editing.opponent} onChange={e=>setEditing({...editing,opponent:e.target.value})}/><input placeholder="Número do processo" value={editing.caseNumber} onChange={e=>setEditing({...editing,caseNumber:e.target.value})}/><select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as LegalCase["status"]})}><option>Ativo</option><option>Encerrado</option></select><label>Data inicial do prazo<input type="date" value={editing.deadlineStart||""} onChange={e=>setEditing({...editing,deadlineStart:e.target.value})}/></label><label>Dias úteis do prazo<input type="number" min="1" placeholder="Ex.: 15" value={editing.deadlineDays||""} onChange={e=>setEditing({...editing,deadlineDays:e.target.value?Number(e.target.value):undefined})}/></label><label>Vencimento confirmado<input type="date" value={editing.deadline} onChange={e=>setEditing({...editing,deadline:e.target.value})}/></label><input placeholder="Área / categoria" value={editing.category||""} onChange={e=>setEditing({...editing,category:e.target.value})}/></div><textarea placeholder="Anotações, estratégia, providências e informações importantes" value={editing.notes} onChange={e=>setEditing({...editing,notes:e.target.value})}/><div className="case-editor-actions"><button onClick={()=>{if(!editing.documents.includes(currentFile))setEditing({...editing,documents:[...editing.documents,currentFile]})}}><FileText/> Vincular documento atual</button><button className="primary action-button" onClick={()=>save(editing)}><Save/> Salvar caso</button></div></div>}
  {visible.length?<div className="case-grid">{visible.map(c=>{const expanded=expandedId===c.id;return <article className={"case-card "+(expanded?"expanded":"collapsed")} key={c.id}>
   <div className="case-card-click" onClick={()=>setExpandedId(expanded?null:c.id)} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setExpandedId(expanded?null:c.id)}}}>
    <div className="case-card-top"><span><small>{c.category||"Direito Aéreo"}{c.caseNumber?" · "+c.caseNumber:""}</small><h3>{c.title||c.client}</h3></span><span className="case-top-actions"><em className={"case-status "+c.status.toLowerCase()}>{c.status}</em><i className={"case-expand-icon "+(expanded?"open":"")}><ChevronRight/></i></span></div>
    {c.sourceKey&&<label className="auto-case"><Sparkles/> Estruturado automaticamente</label>}
    {!expanded&&<div className="case-collapsed-meta"><span><FileText/> {c.documents.length} documento(s)</span><span><Users/> Partes e análise completa</span>{c.deadline&&<span><AlertTriangle/> Prazo {new Date(c.deadline+"T12:00:00").toLocaleDateString("pt-BR")}</span>}</div>}
   </div>
   {expanded&&<div className="case-expanded">
    <section className="case-detail-section case-parties-detail"><h4>Partes</h4><div className="case-parties"><p><CircleUserRound/><span><small>Cliente / parte autora</small><b>{c.client||"Não informado"}</b></span></p><p><Users/><span><small>Parte contrária / parte ré</small><b>{c.opponent||"Não informado"}</b></span></p></div>{c.caseNumber&&<p className="case-number-detail"><small>Número do processo</small><b>{c.caseNumber}</b></p>}</section>
    {c.summary&&<section className="case-detail-section"><h4>Síntese do caso</h4><p>{c.summary}</p></section>}
    <CaseDataSection title="Fatos" items={c.facts}/>
    <CaseDataSection title="Cronologia" items={c.chronology}/>
    <CaseDataSection title="Pedidos" items={c.claims}/>
    <CaseDataSection title="Teses jurídicas" items={c.theses}/>
    <CaseDataSection title="Provas e documentos mencionados" items={c.evidence}/>
    <CaseDataSection title="Riscos e pontos de atenção" items={c.risks}/>
    <CaseDataSection title="Jurisprudência citada" items={c.jurisprudence}/>
    {c.deadline&&<section className="case-detail-section deadline-detail"><h4>Prazo</h4><p><AlertTriangle/> Vencimento confirmado: <b>{new Date(c.deadline+"T12:00:00").toLocaleDateString("pt-BR")}</b>{c.deadlineDays?" · "+c.deadlineDays+" dias úteis":""}</p></section>}
    {c.notes&&<section className="case-detail-section"><h4>Anotações</h4><p>{c.notes}</p></section>}
    <section className="case-detail-section case-files-section"><h4>Arquivos relacionados <b>{c.documents.length}</b></h4>{c.documents.length?<div className="case-documents-list">{c.documents.map((doc,i)=>{const label=doc.split("/").pop()?.replace(/^[a-f0-9]{64}-/,"")||doc;const stored=doc.includes("/");return <div className="case-document-row" key={doc+"-"+i}><FileText/><span><b>{label}</b><small>{stored?"Arquivo privado vinculado a este caso":"Referência legada do documento"}</small></span>{stored&&<span className="case-file-actions"><a href={"/api/documents?path="+encodeURIComponent(doc)} target="_blank" rel="noopener noreferrer">Abrir</a><a href={"/api/documents?download=1&path="+encodeURIComponent(doc)} download><Download/> Baixar</a></span>}</div>})}</div>:<p>Nenhum arquivo vinculado a este caso.</p>}</section>
    <div className="case-meta"><span><FileText/> {c.documents.length} documento(s)</span><span><Gavel/> {Array.isArray(c.jurisprudence)?c.jurisprudence.length:0} precedentes</span><span>Atualizado {c.updatedAt}</span></div>
    <div className="case-actions"><button onClick={()=>setEditing(c)}><Pencil/> Editar</button><button className="danger" disabled={deletingId===c.id} onClick={()=>remove(c.id)}><Trash2/> {deletingId===c.id?"Excluindo...":"Excluir"}</button></div>
   </div>}
  </article>})}</div>:<EmptyCollection icon={<FolderKanban/>} title="Nenhum caso nesta categoria" text="Os novos documentos analisados pelo AeroLex passam a aparecer aqui automaticamente, sem apagar os casos anteriores."/>}
 </div>
}

function Library({query,saveCitation}:{query:string;saveCitation:(a:string,b:string,c?:string)=>void}){const refs=[
 {title:"Código de Defesa do Consumidor",meta:"Lei nº 8.078/1990",tag:"Legislação",text:"Responsabilidade objetiva do fornecedor por defeitos relativos à prestação dos serviços.",source:"CDC · art. 14"},
 {title:"Código Brasileiro de Aeronáutica",meta:"Lei nº 7.565/1986",tag:"Legislação",text:"Regras especiais aplicáveis ao transporte aéreo e à responsabilidade do transportador.",source:"CBA"},
 {title:"Resolução ANAC nº 400",meta:"Condições gerais de transporte aéreo",tag:"Regulação",text:"Direitos do passageiro em casos de atraso, cancelamento, interrupção e preterição.",source:"ANAC · Resolução 400"},
 {title:"Tema 210 do STF",meta:"Convenções internacionais e transporte aéreo",tag:"Jurisprudência",text:"Prevalência das convenções internacionais nos limites dos danos materiais em transporte aéreo internacional.",source:"STF · Tema 210"}
 ].filter(x=>(x.title+x.meta+x.tag).toLowerCase().includes(query.toLowerCase()));return <div className="library-grid">{refs.map(x=><article key={x.title}><label>{x.tag}</label><h3>{x.title}</h3><small>{x.meta}</small><p>{x.text}</p><button onClick={()=>saveCitation(x.title,x.text,x.source)}><Highlighter/> Salvar como citação</button></article>)}</div>}

function SavedCitations({items,update}:{items:SavedCitation[];update:(x:SavedCitation[])=>void}){const [custom,setCustom]=useState(false);const [draft,setDraft]=useState({title:"",text:"",source:"",notes:""});const add=()=>{if(!draft.title.trim()||!draft.text.trim())return;update([...items,{...draft,id:crypto.randomUUID()}]);setDraft({title:"",text:"",source:"",notes:""});setCustom(false)};return <>{custom&&<div className="editor-card"><div><b>Nova citação</b><button onClick={()=>setCustom(false)}><X/></button></div><input placeholder="Título ou assunto" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><textarea placeholder="Cole aqui o trecho da jurisprudência" value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})}/><input placeholder="Tribunal, processo, relator ou fonte" value={draft.source} onChange={e=>setDraft({...draft,source:e.target.value})}/><button className="primary action-button" onClick={add}><Save/> Salvar citação</button></div>}<button className="outline-action" onClick={()=>setCustom(true)}><Plus/> Nova citação manual</button>{items.length?<div className="saved-list">{items.map(x=><article key={x.id}><div><label>Citação salva</label><button className="danger" onClick={()=>update(items.filter(y=>y.id!==x.id))}><Trash2/></button></div><h3>{x.title}</h3><blockquote>“{x.text}”</blockquote><small>{x.source||"Fonte não informada"}</small></article>)}</div>:<EmptyCollection icon={<Highlighter/>} title="Nenhuma citação salva" text="Salve trechos da análise, da biblioteca ou cadastre uma jurisprudência manualmente."/>}</>}

function SavedTheses({items,update}:{items:SavedThesis[];update:(x:SavedThesis[])=>void}){const [custom,setCustom]=useState(false);const [draft,setDraft]=useState({title:"",summary:"",foundation:""});const add=()=>{if(!draft.title.trim()||!draft.summary.trim())return;update([...items,{...draft,id:crypto.randomUUID()}]);setDraft({title:"",summary:"",foundation:""});setCustom(false)};return <>{custom&&<div className="editor-card"><div><b>Nova tese</b><button onClick={()=>setCustom(false)}><X/></button></div><input placeholder="Nome da tese" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><textarea placeholder="Estruture o argumento principal" value={draft.summary} onChange={e=>setDraft({...draft,summary:e.target.value})}/><input placeholder="Fundamento legal ou jurisprudencial" value={draft.foundation} onChange={e=>setDraft({...draft,foundation:e.target.value})}/><button className="primary action-button" onClick={add}><Save/> Salvar tese</button></div>}<button className="outline-action" onClick={()=>setCustom(true)}><Plus/> Nova tese manual</button>{items.length?<div className="saved-list thesis-bank">{items.map(x=><article key={x.id}><div><label>Tese jurídica</label><button className="danger" onClick={()=>update(items.filter(y=>y.id!==x.id))}><Trash2/></button></div><h3>{x.title}</h3><p>{x.summary}</p><small><Scale/> {x.foundation||"Fundamento a complementar"}</small></article>)}</div>:<EmptyCollection icon={<Scale/>} title="Seu banco de teses está vazio" text="Salve uma tese identificada na análise ou cadastre sua própria estrutura argumentativa."/>}</>}

function EmptyCollection({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="empty-collection"><i>{icon}</i><h3>{title}</h3><p>{text}</p></div>}

function ProfileModal({profile,close,save}:{profile:Profile;close:()=>void;save:(p:Profile)=>void}){const [draft,setDraft]=useState(profile);return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="profile-modal"><header><span><i>{initials(draft.name)}</i><div><small>Conta profissional</small><h2>Configurar perfil</h2></div></span><button onClick={close}><X/></button></header><label>Nome completo<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>E-mail<input type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><div className="profile-grid"><label>OAB<input placeholder="UF 000.000" value={draft.oab} onChange={e=>setDraft({...draft,oab:e.target.value})}/></label><label>Escritório<input placeholder="Nome do escritório" value={draft.office} onChange={e=>setDraft({...draft,office:e.target.value})}/></label></div><footer><button onClick={close}>Cancelar</button><button className="primary" onClick={()=>save(draft)}><Save/> Salvar perfil</button></footer></section></div>}

function Loading(){return <div className="loading"><i><Sparkles/></i><h2>Estruturando o documento</h2><p>Identificando partes, fatos, citações, teses, provas e riscos.</p><div><span/></div></div>}
function Empty({analyze,pick}:{analyze:()=>void,pick:()=>void}){return <div className="loading"><i><UploadCloud/></i><h2>Documento pronto para análise</h2><p>Inicie a leitura estruturada ou substitua o arquivo.</p><button onClick={pick}>Substituir</button> <button className="primary" onClick={analyze}><Sparkles/> Analisar documento</button></div>}
function Blocked({pick}:{pick:()=>void}){return <div className="loading blocked"><i><AlertTriangle/></i><h2>Não foi possível estruturar este PDF</h2><p>O PDF foi preservado, mas a análise automática falhou. Tente novamente ou envie outro arquivo. Nenhum caso incompleto foi criado.</p><button onClick={pick}>Escolher outro arquivo</button></div>}
